export function DisclaimerBanner() {
  return (
    <div className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900">
      <p className="font-semibold">⚠️ Pilot / MVP — not for medical use</p>
      <p className="mt-1 leading-relaxed">
        This is an experimental research tool. Results are{" "}
        <span className="font-semibold">suggested possible matches only</span> and
        may be wrong. Do <span className="font-semibold">not</span> use it to
        identify, take, or administer any medication. Always confirm with a
        pharmacist, physician, or the official packaging.
      </p>
    </div>
  );
}

export function DisclaimerFooter() {
  return (
    <footer className="mt-12 border-t border-slate-200 pt-6 text-xs leading-relaxed text-slate-500">
      <p>
        <span className="font-semibold">Disclaimer:</span> This pilot tool is
        provided for research and demonstration purposes only, without warranty
        of any kind. It does not provide medical advice and is not a substitute
        for professional judgment. Predictions are generated by an experimental
        machine-learning model and can be incorrect. Never rely on this tool to
        identify medication. In an emergency, contact a medical professional or
        poison control.
      </p>
    </footer>
  );
}
